#ifndef MCS_SYSOUT_H
#define MCS_SYSOUT_H
/* System output text, including error messages, warnings, prompts, line fragments and format strings */
#define SYSOUT_SHELL_RESTORE_FAILED "Unable to restore previous shell state.\nUsing defaults."
#define SYSOUT_BATCH_CMD_TOO_LONG "Batch command too long"
#define SYSOUT_SHELL_SAVE_WARNING_BASIC "Warning: write error saving shell state.\nProceed to BASIC"
#define SYSOUT_SHELL_SAVE_WARNING_RUN "Warning: write error saving shell state.\nRun program anyway"
#define SYSOUT_WRITE_FAULT_ERR "Write fault error"
#define SYSOUT_VOL_HEADER " Volume in drive %s: is "
#define SYSOUT_CRT_ID_HEADER " Disk ID is 00\n"
#define SYSOUT_DISK_ID_HEADER " Disk ID is %s\n"
#define SYSOUT_YES_NO_SUFFIX " (Y/N)? "
#define SYSOUT_PRESS_ANY_KEY "Press any key to continue . . ."
#define SYSOUT_DRIVE_NUMBER "%u"
#define SYSOUT_INVALID_DRIVE_SPEC "Invalid drive specification"
#define SYSOUT_FILE_NAME_TOO_LONG "File name too long"
#define SYSOUT_INVALID_FILE_NAME "Invalid file name"
#define SYSOUT_CRT_FILE_OP_FAILED "Cartridge file operation failed"
#define SYSOUT_NOT_READY_READING "Not ready reading drive"
#define SYSOUT_DRIVE_NOT_READY "Drive not ready"
#define SYSOUT_DISK_ERR "Disk error:"
#define SYSOUT_CRT_OP_FAILED "Cartridge operation failed"
#define SYSOUT_NESTED_BATCH "Cannot run multiple batch files"
#define SYS_BATCH_TOO_LARGE_OR_UNREADABLE "Batch file too large or unreadable"
#define SYSOUT_INVALID_PARAM "Invalid parameter"
#define SYSOUT_MEM_TOTAL "%10s bytes total memory\n"
#define SYSOUT_MEM_SHELL "%10s bytes shell and workspace\n"
#define SYSOUT_MEM_STACK "%10s bytes reserved for C stack\n"
#define SYSOUT_MEM_ROM_WINDOW "%10s bytes cartridge ROM window\n"
#define SYSOUT_MEM_SYSTEM "%10s bytes reserved for system\n"
#define SYSOUT_MEM_FREE "%10s bytes free\n"
#define SYSOUT_SYNTAX_ERR "Syntax error"
#define SYSOUT_BAD_CMD_OR_FILE_NAME "Bad command or file name"
#define SYSOUT_INVALID_DURATION "Invalid duration"
#define SYSOUT_ECHO_IS_ON "ECHO is on."
#define SYSOUT_ECHO_IS_OFF "ECHO is off."
#define SYSOUT_SYNTAX_BASIC "Syntax: BASIC"
#define SYSOUT_INVALID_CMD "Invalid command"
#define SYSOUT_MULTIPLE_REDIR "Multiple redirections not supported"
#define SYSOUT_REDIR_NOT_SUPPORTED "Redirection not supported for command"
#define SYSOUT_SYNTAX_TYPE "Syntax: TYPE filename [/H:n | /T:n | /HEX]"
#define SYSOUT_FILE_NOT_FOUND "File not found"
#define SYSOUT_UNSUPPORTED_FILE_TYPE "Unsupported file type"
#define SYSOUT_INVALID_DEST "Invalid destination"
#define SYSOUT_PRINTER_REDIR "Printer redirection not supported"
#define SYSOUT_CANNOT_REDIR_FIND_ON_SELF "Cannot redirect FIND onto itself"
#define SYSOUT_CANNOT_REDIR_TYPE_ON_SELF "Cannot redirect TYPE onto itself"
#define SYSOUT_DEST_MUST_BE_SEQ "Destination must be a SEQ file"
#define SYSOUT_TYPE_DEL "DEL"
#define SYSOUT_TYPE_PRG "PRG"
#define SYSOUT_TYPE_SEQ "SEQ"
#define SYSOUT_TYPE_USR "USR"
#define SYSOUT_TYPE_REL "REL"
#define SYSOUT_TYPE_UNKNOWN "???"
/* Editor */
#define SYSOUT_SAVING "Saving . . ."
#define SYSOUT_INVALID_SWITCH "Invalid switch"
#define SYSOUT_TOO_MANY_PARAMS "Too many parameters"
#define SYSOUT_FILE_TOO_LARGE_OR_UNREADABLE "File too large or unreadable"
#define SYSOUT_EDIT_INITIAL_POS " 01:01  "
#define SYSOUT_UNTITLED "Untitled"
#define SYSOUT_RUN_STOP_QUIT "RUN/STOP:quit"
#define SYSOUT_SAVE_CHANGES "Save changes"
#define SYSOUT_FILE_NAME "File name: "
/* File display, search, launch and help */
#define SYSOUT_SYNTAX_PRINT "Syntax: PRINT filename [4:|5:|LPT1|LPT2]"
#define SYSOUT_INVALID_PRINTER "Invalid device (4:, 5:, LPT1, LPT2)"
#define SYSOUT_PRINTER_NOT_READY "Device not ready"
#define SYSOUT_READ_FAULT_ERR "Read fault error"
#define SYSOUT_SYNTAX_FIND "Syntax: FIND [switches] \"string\" filename"
#define SYSOUT_FIND_HEADER "---- %s"
#define SYSOUT_FIND_LINE_NUMBER "[%s]"
#define SYSOUT_FIND_COUNT ": %s\n"
#define SYSOUT_SYNTAX_RUN "Syntax: RUN file [/A address]"
#define SYSOUT_INVALID_SWITCH_BATCH "Invalid switch for batch file"
#define SYSOUT_INVALID_LOAD_ADDR "Invalid load address"
#define SYSOUT_LOADING "Loading . . ."
#define SYSOUT_CANNOT_LOAD_CRT_PRG "Cannot load cartridge program"
#define SYSOUT_CRT_HELP_UNAVAILABLE "Help unavailable"
#define SYSOUT_HELP_INTRO "For more information on a specific\ncommand, type HELP [command]."
#define SYSOUT_HELP_CMD "%-13s"
#define SYSOUT_HELP_ALIASES "Aliases: DELETE ERASE RENAME VERSION"
/* Directory listings and file management */
#define SYSOUT_DIR_HEADER " Directory of %s:\n\n"
#define SYSOUT_DIR_WIDE_ENTRY "%-19s"
#define SYSOUT_DIR_ENTRY "%-17s%s%8s"
#define SYSOUT_DIR_BLOCKS " (%3s bl)"
#define SYSOUT_DIR_TOTAL "%3u File(s)%11s bytes"
#define SYSOUT_DIR_BLOCKS_LINE " (%3s bl)\n"
#define SYSOUT_DIR_FREE "%17s bytes free"
#define SYSOUT_FILE_COPY_ON_SELF "File cannot be copied onto itself"
#define SYSOUT_COPY_NOT_COMPLETED "Copy not completed"
#define SYSOUT_SYNTAX_MOVE "Syntax: MOVE source destination [/P]"
#define SYSOUT_SYNTAX_COPY "Syntax: COPY source destination [/P]"
#define SYSOUT_WILDCARDS_DEST_DRV "Wildcards require a destination drive"
#define SYSOUT_FILES_COPIED "        %u file(s) copied.\n"
#define SYSOUT_ONE_FILE_MOVED "        1 file(s) moved."
#define SYSOUT_ONE_FILE_COPIED "        1 file(s) copied."
#define SYSOUT_FILE_IS_LOCKED "File is locked"
#define SYSOUT_ERR_READING_BANK_DIR "Error reading bank directory"
#define SYSOUT_SYNTAX_DEL "Syntax: DEL filename [/P]"
#define SYSOUT_DELETE_FILE "Delete %s"
#define SYSOUT_DELETE_THIS_FILE "Delete this file"
#define SYSOUT_ATTR_ENTRY "  %c    %s\n"
#define SYSOUT_INVALID_BANK_DIR_CHAIN "Invalid bank directory chain"
#define SYSOUT_FILES_SAME_DISK "Files must be on the same disk"
#define SYSOUT_FILE_LIST_TOO_LONG "File list too long"
#define SYSOUT_SYNTAX_REN "Syntax: REN oldname newname"
#define SYSOUT_CANNOT_RENAME_ACROSS_DRIVES "Cannot rename across drives"
#define SYSOUT_DIR_TOO_LARGE "Directory too large"
#define SYSOUT_OVERWRITE_FILE "Overwrite existing file"
/* Disk commands */
#define SYSOUT_UNSUPPORTED_OP_CRT "Unsupported operation on cartridge"
#define SYSOUT_UNSUPPORTED_DRIVE_TYPE "Unsupported drive type"
#define SYSOUT_UNSUPPORTED_DISK_FORMAT "Unsupported disk format"
#define SYSOUT_INVALID_REL_FILE "Invalid REL file"
#define SYSOUT_CHECKING_AND_FIXING_DISK "Checking and fixing disk . . ."
#define SYSOUT_DISK_VALIDATION_FAILED "Disk validation failed"
#define SYSOUT_DISK_VALIDATION_COMPLETE "Disk validation complete"
#define SYSOUT_DISK_VOL "Volume %s\n"
#define SYSOUT_DISK_ID_SPACED "Disk ID is %c%c\n\n"
#define SYSOUT_DISK_TOTAL_SPACE "%7s bytes total disk space\n"
#define SYSOUT_DISK_ALLOCATED "%7s bytes allocated in %u files\n"
#define SYSOUT_DISK_AVAILABLE "%7s bytes available on disk\n\n"
#define SYSOUT_DISK_BLOCK_SIZE "    256 bytes in each block (254 usable)"
#define SYSOUT_DISK_TOTAL_BLOCKS "%7s total blocks on disk\n"
#define SYSOUT_DISK_FREE_BLOCKS "%7s available blocks on disk\n\n"
#define SYSOUT_SYNTAX_LABEL "Syntax: LABEL [drive:] [name]"
#define SYSOUT_VOLUME_LABEL_TOO_LONG "Volume label too long"
#define SYSOUT_LABEL_VOLUME "Volume in drive %s: is %s\n"
#define SYSOUT_LABEL_DISK_ID "Disk ID is %c%c\n"
#define SYSOUT_LABEL_PROMPT "Volume label  (16 characters)? "
#define SYSOUT_VOL_LABEL_CHANGED "Volume label changed"
#define SYSOUT_SYNTAX_FORMAT "Syntax: FORMAT drive:"
#define SYSOUT_INSERT_DISK "Insert disk in drive %s:\n"
#define SYSOUT_ALL_DATA_LOST "All data on this disk will be lost!"
#define SYSOUT_PROCEED_WITH_FORMAT "Proceed with format"
#define SYSOUT_FORMAT_LABEL_PROMPT "Volume label (16 characters): "
#define SYSOUT_DISK_ID_PROMPT "New disk ID (2 letters or digits): "
#define SYSOUT_DISK_ID_FORMAT "Disk ID must be two letters or digits"
#define SYSOUT_FORMATTING "Formatting . . ."
#define SYSOUT_FORMAT_COMPLETE "Format complete"
#define SYSOUT_SYNTAX_DISKID "Syntax: DISKID [drive:] [id]"
#define SYSOUT_SYNTAX_DISKINIT "Syntax: DISKINIT [drive:]"
#define SYSOUT_INVALID_DISK_ID "Invalid disk ID"
#define SYSOUT_DISK_ID_CHANGED "Disk ID changed"
#define SYSOUT_SYNTAX_DISKCOPY "Syntax: DISKCOPY source: destination:"
#define SYSOUT_TWO_DIFF_DRIVES "Two different drives required"
#define SYSOUT_INCOMPATIBLE_DRIVE "Incompatible drive model"
#define SYSOUT_DEST_DISK_OVERWRITTEN "Destination disk will be overwritten"
#define SYSOUT_DISKCOPY_PROCEED "Proceed with disk copy"
#define SYSOUT_COPY_TRACK_PROGRESS "Copying track %u of %u\n"
#define SYSOUT_COPY_COMPLETE "Copy complete"
#define SYSOUT_DISK_COPY_NOT_COMPLETED "Disk copy not completed"
/* Startup and environment */
#define SYSOUT_INVALID_COLOR "Invalid color"
#define SYSOUT_INVALID_CHARSET_NAME "Invalid charset name"
#define SYSOUT_USE_HELP_SET "Use HELP SET"
#define SYSOUT_ENV_STATS "%3u bytes total environment size\n%3u bytes used\n%3u bytes free\n"
#define SYSOUT_ENV_INVALID_VALUE "Invalid value"
#define SYSOUT_ENV_FULL "Environment full"
#define SYSOUT_CRT_FS_UNAVAILABLE "Cartridge filesystem unavailable"
#define SYSOUT_INVALID_DIRECTIVE "Invalid CONFIG.SYS directive"
#define SYSOUT_CANNOT_LOAD "Cannot load %s"
#define SYSOUT_SPLASH_PRODUCT "MCS-DOS version " VERSION
#define SYSOUT_COPYRIGHT "Copyright (C) 2026 MCS Labs"
/* Cartridge filesystem statistics */
#define SYSOUT_CRT_VOL "Volume MCS-DOS 2.0\nDisk ID is MC\n\n"
/* VER banner */
#define SYSOUT_BANNER "MCS-DOS Version " VERSION "\nCopyright (C) 2026 MCS Labs"
/* Tape copy */
#define SYSOUT_SYNTAX_TAPECOPY "Syntax: TAPECOPY [filename] [drive:]"
#define SYSOUT_SHELL_SAVE_ERR "Failed saving shell state"
#define SYSOUT_TAPE_KERNAL "Could not locate standard KERNAL tape\nreader (custom ROM installed?)"
#define SYSOUT_TAPE_PLAY "Press play on tape"
#define SYSOUT_TAPE_FOUND "Found "
#define SYSOUT_TAPE_SAVE_TO "Save to drive "
#define SYSOUT_TAPE_QUESTION "?"
#define SYSOUT_TAPE_YES_NO " (Y/N) "
#define SYSOUT_TAPE_FILENAME "Filename (ENTER for default name): "
#define SYSOUT_TAPE_EXISTS "File already exists."
#define SYSOUT_TAPE_LOADING "Loading"
#define SYSOUT_TAPE_SAVING "Saving"
#define SYSOUT_TAPE_SAVED "Saved"
#define SYSOUT_TAPE_NEXT "Load next file from tape?"
#define SYSOUT_TAPE_CANCELLED "Tape transfer cancelled"
#define SYSOUT_TAPE_TOO_LARGE "Tape program too large"
#define SYSOUT_TAPE_READ_ERR "Tape read error or unsupported format"
#define SYSOUT_TAPE_END "End of tape"
#define SYSOUT_TAPE_UNSUPPORTED "Unsupported tape"
#define SYSOUT_TAPE_CLEANUP_ERROR "Transfer failed: cannot delete partial\nfile"
/* Cartridge journal compaction */
#define SYSOUT_COMPACT_CRT_ONLY "Drive is not system cartridge"
#define SYSOUT_COMPACT_FAIL "File system compaction failed"
#define SYSOUT_COMPACT_COMPLETE "Cartridge journal compacted."
#define SYSOUT_ALREADY_COMPACT "Cartridge journal already compact."
/* CHKDSK drive stats */
#define SYSOUT_DRIVE_MODEL "Drive model is %s\n"
#define SYSOUT_VOL_ID "Drive identifier is %u (CBM) / %c (DOS)\n"
#define SYSOUT_VOL_ID_CART "Drive identifier is 0"
#endif
